def my_game():
    print("* * * * * * * * * * * * * * * * * *")
    print("* * * * * * * * * * * * * * * * * *")
    print("Welcome to the 🂡 'Game of Wonder!' 🂡")
    print("")
    print("You have fallen down a rabbit hole & the only way out is through.")
    print("Would you like to carry on? Or just give up now?")
    print("* * * * * * * * * * * * * * * * * *")
    print("Enter: (y) to carry on!")
    print("- or -")
    print("Enter: (n) to give up...")
    print("* * * * * * * * * * * * * * * * * *")
    input1 = input()
    if input1 == "n":
        print("")
        print("")
        print("")
        print("")
        print("* * * * * * * * * * * * * * * * * *")
        print("- - - THE RESULT OF YOUR CHOICE - - -")
        print("")
        print("The ♥️👑  Queen  👑♥️  caught you.")
        print("And... off with your head.   🪓💀")
        print("")
        print("But this is the Game of Wonder")
        print("...where not even a beheading is an escape...")
        print("")
        print("...the only way out is through...")
        print("")
        print("... you will awake in...")
        print("...3")
        print("...2")
        print("...1")
        print("")
        print("")
        my_game()
    elif input1 == 'y':
        print("")
        print("")
        print("")
        print("")
        print("* * * * * * * * * * * * * * * * * *")
        print("- - - THE RESULT OF YOUR CHOICE - - -")
        print("")
        print("The game begins!")
        print("")
        print("You are walking down a long hallway and come to two doors...")
        print("🚪🚪")
        print("🟣  A purple one on the left...")
        print("🟢 A green one on the right...")
        print("* * * * * * * * * * * * * * * * * *")
        print("You must choose a door to pass thorugh")
        print("Enter: (p) for 'Purple Door'")
        print("- or -")
        print("Enter: (g) for 'Green Door'")
        print("* * * * * * * * * * * * * * * * * *")
        door_choice = input()
        if door_choice == "p":
            print("")
            print("")
            print("")
            print("")
            print("* * * * * * * * * * * * * * * * * *")
            print("- - - THE RESULT OF YOUR CHOICE - - -")
            print("")
            print("You pass through the purple door...")
            print("The good news is that you are not dead...")
            print("The bad news is that you gave been turned into a mouse...")
            print("🐭")
            print("This is fine... Just fine... You can keep going.")
            print("")
            print("The mouse version of you finds yourself in a room with...")
            print("A window 🪟")
            print("And a plate of cheese 🧀")
            print(
                "The door SLAMS shut behind you & the room begins filling with water...")
            print("")
            print("* * * * * * * * * * * * * * * * * *")
            print("What do you do?")
            print("Enter: (w) to jump out the window")
            print("- or -")
            print("Enter: (c) to eat the cheese")
            print("* * * * * * * * * * * * * * * * * *")
            purple_room_choice = input()
            if purple_room_choice == "w":
                print("")
                print("")
                print("")
                print("")
                print("* * * * * * * * * * * * * * * * * *")
                print("- - - THE RESULT OF YOUR CHOICE - - -")
                print("")
                print("You jumped out the window")
                print(
                    "A flamingo swoops down from the sky and snatches you up in her talons!")
                print("🦩")
                print("")
                print("* * * * * * * * * * * * * * * * * *")
                print("What do you do?")
                print("Enter: (b) to bite the flamingo and fight for your life")
                print("- or -")
                print("Enter: (s) to sing your desth song... This is the end...")
                print("* * * * * * * * * * * * * * * * * *")
                flamingo_choice = input()
                if flamingo_choice == "s":
                    print("")
                    print("")
                    print("")
                    print("")
                    print("* * * * * * * * * * * * * * * * * *")
                    print("- - - THE RESULT OF YOUR CHOICE - - -")
                    print("")
                    print("You sing your death song...")
                    print("But wait...")
                    print("The flamingo is actually a cursed princess...")
                    print("She delivers you out of Wonderland.")
                    print("")
                    print("🎆  You are still a mouse... But YOU WIN! 🎆")
                    print("")
                    print("* * * * * * * * * * * * * * * * * *")
                    print("Would you like to play again?")
                    print("Enter: (z) to just go home!")
                    print("- or -")
                    print("Enter: (m) to go back in!")
                    print("* * * * * * * * * * * * * * * * * *")
                    replay_1 = input()
                    if replay_1 == "z":
                        print("")
                        print("")
                        print("")
                        print("")
                        print("Thank you for playing.")
                        print("I hope to see you down the rabbit hole again.")
                    elif replay_1 == "m":
                        print("")
                        print("")
                        print("")
                        print("")
                        print("Very well... We're all a little mad here, arent we?")
                        my_game()
                elif flamingo_choice == "b":
                    print("")
                    print("")
                    print("")
                    print("")
                    print("* * * * * * * * * * * * * * * * * *")
                    print("- - - THE RESULT OF YOUR CHOICE - - -")
                    print("")
                    print("You bite the flamingo...")
                    print("She flinches and drops you...")
                    print("You fall and fall and fall into a pit of rusty nails")
                    print("")
                    print("But this is the Game of Wonder")
                    print(
                        "...where not even a plummeting to a sharp rusty doom is an escape...")
                    print("")
                    print("...the only way out is through...")
                    print("")
                    print("... you will awake in...")
                    print("...3")
                    print("...2")
                    print("...1")
                    print("")
                    print("")
                    my_game()
            elif purple_room_choice == "c":
                print("")
                print("")
                print("")
                print("")
                print("* * * * * * * * * * * * * * * * * *")
                print("- - - THE RESULT OF YOUR CHOICE - - -")
                print("")
                print("You eat the cheese! 🧀")
                print("It is delicious!")
                print("... but what is that? ... the water is going down?")
                print("No... You are going up!")
                print("The cheese turns you back into a human")
                print("But the room is still filling with water")
                print("")
                print(
                    "There is still a window... But there is also a hatch in the ceiling?")
                print("* * * * * * * * * * * * * * * * * *")
                print("What do you do?")
                print("Enter: (w) to jump out the window")
                print("- or -")
                print(
                    "Enter: (s) to swim as the rater rises & try to escape through the hatch ")
                print("* * * * * * * * * * * * * * * * * *")
                water_choice = input()
                if water_choice == "w":
                    print("")
                    print("")
                    print("")
                    print("")
                    print("* * * * * * * * * * * * * * * * * *")
                    print("- - - THE RESULT OF YOUR CHOICE - - -")
                    print("")
                    print("You jump out the window")
                    print("...The 18th story window...")
                    print("Splat! 💀")
                    print("")
                    print("But this is the Game of Wonder")
                    print(
                        "...where not even a freedalling 18 stories is an escape...")
                    print("")
                    print("...the only way out is through...")
                    print("")
                    print("... you will awake in...")
                    print("...3")
                    print("...2")
                    print("...1")
                    print("")
                    print("")
                    my_game()
                elif water_choice == "s":
                    print("")
                    print("")
                    print("")
                    print("")
                    print("* * * * * * * * * * * * * * * * * *")
                    print("- - - THE RESULT OF YOUR CHOICE - - -")
                    print("")
                    print("You wait and swim.")
                    print("The water reaches the top...")
                    print("You thow the hatch open and climb through...")
                    print("You find yourself on the roof of Buckingham Palace")
                    print("")
                    print("🎆  You are in a new predicament... But YOU WIN! 🎆")
                    print("")
                    print("* * * * * * * * * * * * * * * * * *")
                    print("Would you like to play again?")
                    print("Enter: (z) to just go home!")
                    print("- or -")
                    print("Enter: (m) to go back in!")
                    print("* * * * * * * * * * * * * * * * * *")
                    replay_2 = input()
                    if replay_2 == "z":
                        print("")
                        print("")
                        print("")
                        print("")
                        print("Thank you for playing.")
                        print("I hope to see you down the rabbit hole again.")
                    elif replay_2 == "m":
                        print("")
                        print("")
                        print("")
                        print("")
                        print("Very well... We're all a little mad here, arent we?")
                        my_game()
        elif door_choice == "g":
            print("")
            print("")
            print("")
            print("")
            print("* * * * * * * * * * * * * * * * * *")
            print("- - - THE RESULT OF YOUR CHOICE - - -")
            print("")
            print("You pass through the green door")
            print("You isntantly turn into a blueberry filled cupcake...")
            print("🧁")
            print("")
            print("* * * * * * * * * * * * * * * * * *")
            print("What do you do?")
            print(
                "Enter: (w) to wait... because you are a cupcake... What else is there to do?")
            print("- or -")
            print(
                "Enter: (t) to try telekenesis... because you are a cupcake... What else is there to do?")
            print("* * * * * * * * * * * * * * * * * *")
            cupcake_choice = input()
            if cupcake_choice == "w":
                print("")
                print("")
                print("")
                print("")
                print("* * * * * * * * * * * * * * * * * *")
                print("- - - THE RESULT OF YOUR CHOICE - - -")
                print("")
                print("You wait...")
                print("🧁🕰")
                print("")
                print("You are beginning to feel hopless... but what is that you hear?")
                print("Laughter... The sound of children?")
                print(
                    "A swarm of toddlers bursts into the room and devour you... Your sticky blueberry innards spilling everywhere!")
                print("There is not a crumb of you left.")
                print("")
                print("But this is the Game of Wonder")
                print(
                    "...where not even being grusomely eaten alive is an escape...")
                print("")
                print("...the only way out is through...")
                print("")
                print("... you will awake in...")
                print("...3")
                print("...2")
                print("...1")
                print("")
                print("")
                my_game()
            elif cupcake_choice == "t":
                print("")
                print("")
                print("")
                print("")
                print("* * * * * * * * * * * * * * * * * *")
                print("- - - THE RESULT OF YOUR CHOICE - - -")
                print("")
                print("You use telekenesis... Even though it is hopeless")
                print("But what is this?")
                print(
                    "A boy with red curly heair comes in and eats you in a single bite!")
                print("Inside his stomach, you hear... a... horn honking?")
                print("You may be losing your mind... but it is a...")
                print("SCHOOL BUS?!?! 🚌")
                print(
                    "A woman with a shrill voice and crazy red hair invites you into the bus.")
                print(
                    "You go with her... She uses science magic from her bus to teach you science & return you to your human form...")
                print("The boy 'passes' the bus... back in the real world...")
                print("")
                print("🎆  You are a fourth grader again... But YOU WIN! 🎆")
                print("")
                print("* * * * * * * * * * * * * * * * * *")
                print("Would you like to play again?")
                print("Enter: (z) to just go home!")
                print("- or -")
                print("Enter: (m) to go back in!")
                replay_3 = input()
                if replay_3 == "z":
                    print("")
                    print("")
                    print("")
                    print("")
                    print("Thank you for playing.")
                    print("I hope to see you down the rabbit hole again.")
                elif replay_3 == "m":
                    print("")
                    print("")
                    print("")
                    print("")
                    print("Very well... We're all a little mad here, arent we?")
                    print("* * * * * * * * * * * * * * * * * *")
                    my_game()


my_game()
